{
 "title": "CPU load / Memory usage / Service Availability Dashboard",
 "tags": [
  "cpu",
  "ram",
  "SA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Availability - [1w]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(probe_success{job=\"blackbox\", instance=\"http-echo:5678\"}[1w]) / count_over_time(probe_success{job=\"blackbox\", instance=\"http-echo:5678\"}[1w])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Availability - [24h]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(probe_success{job=\"blackbox\", instance=\"http-echo:5678\"}[24h]) / count_over_time(probe_success{job=\"blackbox\", instance=\"http-echo:5678\"}[24h])) * 100\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"node\"}[5m])) * 100)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"})\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}